# Site settings
title: UNIS-UN
url: http://www.unis-un.org
email: info@unis-un.org
description: "unis-un does stuff"
logo_url: http://www.unis-un.org/img/fb.png
#Upcoming Conference year (Remeber to use quotes)
conf_year: "2016"

#Settings
show_tweets: false
show_sched: false
live: false

# Social media
twitter_username: unis_un
facebook_username: unisunconf
insta_username: unisun_nyc

# Build settings
markdown: kramdown
permalink: pretty


